#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         5
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 desktop='^4' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Thorium-browser desktop='^2'
bspc rule -a kitty desktop='^1'
bspc rule -a thunderbird desktop='^6'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a discord desktop='^6'
bspc rule -a Element desktop='^6'
bspc rule -a Pcmanfm desktop='^5'
bspc rule -a PeaZip desktop='^5'
bspc rule -a Virt-manager desktop='^7'
bspc rule -a Minetest desktop='^9'
bspc rule -a pcsx2-qt desktop='^9'
bspc rule -a mpv desktop='^8'
bspc rule -a nuclear desktop='^8'
bspc rule -a Geany desktop='^3'
bspc rule -a lite-xl desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true

# border colors

bspc config focused_border_color "#6B5468"
bspc config normal_border_color "#FCCEC1"

nitrogen --restore &

$HOME/.config/polybar/launch.sh

kdeconnect-indicator
flameshot
nm-applet
